### ISSUE TITLE
Export matched contents to well-known file formats

### ISSUE THREAD

**Issue by elfring** [comby-tools/comby#150]
[Contents can be found in “holes”](https://comby.dev/#match-syntax "Match syntax reference").
Would you like to support that data which were found in source files can be exported to well-known file formats like CSV, JSON or XML?

**Comment by rvantonder** [comment]
There is support for `json` output via the `-json-lines` option. I'll add this to the quick reference so this is more discoverable. It is only possible to get line/column ranges via the `-match-only` flag. Without the `-match-only` flag, only the `offset` value is given for matches, and their content (the `line/col` locations are `-1`). In time I will add the `line/col` locations without the `-match-only` option.

Some examples for getting or using JSON data can be found in [this PR](https://github.com/comby-tools/comby/pull/126).

Since there are existing tools to convert serializable formats like JSON to others, I don't think it's a priority to support XML/CSV natively.

**Comment by elfring** [comment]
Are the supported JSON data formats documented already?

**Comment by rvantonder** [comment]
Closing this, JSON output documented in https://comby.dev/docs/api

**Comment by elfring** [comment]
Can the JSON output be documented in a more structured format besides examples and “summaries”?
