### ISSUE TITLE
Parse Markdown and Output Markdown

### ISSUE THREAD

**Issue by flow-danny** [comby-tools/comby#157]
Recently I've started using https://github.com/entangled/entangled to write literate style documentation with actual implementation embedded in "```" markdown code blocks.

This is pretty neat, but some filetypes (like JSON) do not have comments and can not be supported this way. It would also sometimes be interesting to represent code or data, in actual markdown format, for example tables.

I see you're already using Comby to [match Markdown and output HTML](https://github.com/comby-tools/comby.dev/tree/master/templates) 

Could I use Comby today to parse Markdown tables, output `package.json` dependencies, and the other way around: generate a table of project dependencies from `package.json`?  Is this something you have considered?

**Comment by rvantonder** [comment]
Hi @flow-danny. Thanks for sharing the context around your project. I haven't had a chance to look into it deeply, but it looks neat.

> Could I use Comby today to parse Markdown tables, output package.json dependencies, and the other way around: generate a table of project dependencies from package.json?

My high-level impression here is "Mostly, yes.", with the caveat that it depends on the input and the matching capabilities of Comby currently, and what the output format looks like. I've used Comby as a 'roll my own templating engine', which sounds similar to what you want. You could do the same, and I would point out that there are two things to take note of that controls parsing for your use case.

1. You can define which syntactic elements are significant in your parsing/transformation. For my own templating engine you see above, I use a kind of parenthesis language where the only thing that I really care about is that `()`, `[]` and `{}` are balanced. This is the [`.dyck`](https://github.com/comby-tools/comby.dev/blob/master/gulpfile.js#L31) language that I use for the website, and that could suit your initial needs. It can then be useful to combine the language definition with a template that rewrites tokens like `\paren` if you need an unbalanced parenthesis in the output, [like I do here](https://github.com/comby-tools/comby.dev/tree/master/templates/verbatim-left-paren). How strongly you want to enforce the syntax is all up to you: maybe `.dyck` is good enough. Other than that, you can completely change and define which syntax is significant (whether syntax denotes a balanced property, comments, or string data). Since you mentioned comments for JSON, you could also add the comment format you want. Have a look at the format and example here on doing so here: https://comby.dev/#faq-language-extension.

2. The second capability that you have is to define specific templates to transform your inputs. Those templates will work with respect to the language definition in (1), and I hope my example with Markdown-like HTML is a good enough source of inspiration.

Note that there's no specific parsing support for entire constructs like "a markdown table" or "a JSON object with keys and values". The transformations are purely syntactic, so the level of interface for transforming those high level pieces will come down to how you define the templates. There are certainly more involved transformations that are hard to write in a one-to-one way, and here you'll either have to make use of [rules](https://comby.dev/#advanced-usage), or it might be outside of Comby's current capabilities. My intuition is that the specific example `package.json` -> `Markdown` or vice versa will likely require rules and may stretch the current capabilities a bit.

If you run into limitations or trouble with the above, ping me on [Gitter](https://gitter.im/comby-tools/community), or here in the issue tracker if you really prefer.

> Is this something you have considered?

I think the closest thing I've considered recently is custom transformations that turn source code into HTML or similar presentation formats for better syntax highlighting (since regex can be limiting for matching a lot of syntactic structures).

**Comment by rvantonder** [comment]
@flow-danny I hope this was useful. If you have any more thoughts on this, please check in with me on the gitter channel.
