### ISSUE TITLE
.comby files

### ISSUE THREAD

**Issue by abitrolly** [comby-tools/comby#163]
**I'm always frustrated when** I need to supply several different file paths as input.

**Describe the solution you'd like**

Self-containing `.comby` file format that contains match template, rewrite template and example in one file.
```
if (:[cond])

---[rewrite]-----
if (1)

---[example]-----
if (fgets(line, 128, file_pointer) == Null) // 1) if (...) returns 0
      return 0;
...
if (scanf("%d) %d", &x, &y) == 2) // 2) if (scanf("%d) %d", &x, &y) == 2) returns 0
      return 0; 

```

**Additional context**
Or it could be a simplate - https://simplates.org/

**Comment by abitrolly** [comment]
Basically it can simplify applying of subset of https://github.com/comby-tools/sample-catalog

**Comment by rvantonder** [comment]
Yeah, agree this is a bit painful. Part of the intention is to separate the inputs so that escaping/metasyntax isn't needed to delineate/separate the match and rewrite templates. That said, agree it should be possible to specify these in a single file somehow.

`spatch` format is another way of achieving this, and also allows shorter templates by deduplicating common parts. See related issue #149 and http://coccinelle.lip6.fr/sp.php. What do you think of that format?

**Comment by abitrolly** [comment]
@rvantonder maybe that's not that important when it is possible to specify a path to a template dir. The problem was to discover the right syntax.
```
comby -templates catalogue/Python2 -d . -f generate.py
```
Specifying `generate.py` instead of `-f generate.py` didn't work and complained about missing match and rewrite templates.

Do `spatch` I did't find `@@` self-explanatory or intuitive enough. I've heard about `coccinelle` before, and without sufficient background terms like `kinds of collateral evolutions` escape from my understanding, so I don't know how it is supposed to apply those patches. Maybe they should not invert the meaning of green and red colors.

**Comment by rvantonder** [comment]
Sorry for the delay in response, I was ill and in bed all last week :(

>Specifying generate.py instead of -f generate.py didn't work and complained about missing match and rewrite templates.

Ah, right. That's because some confusion happens with `-templates` and the anonymous arguments (`-f` exists to be used with templates). This issue is related to #161. When fixed, you should be able to specify just `generate.py` without the `-f`.

In general, if you have an idea to make specifying multiple templates easier (or think that the `.comby` format you mentioned above will improve things), then I'll keep this open to track a possible solution.

---

> I did't find @@ self-explanatory or intuitive enough

I feel the same.

**Comment by abitrolly** [comment]
No pressure. Feeling well should always be a top priority. ,)

As for the workflow improvement, reading `template` dir from a `.zip` archive can be more convenient for sharing the rules. The https://comby.live/ can also provide an option to import/export them. Even in uncompressed format.

**Comment by rvantonder** [comment]
I like the zip idea!

**Comment by rvantonder** [comment]
I'm adding a way to read patterns using a TOML file in #189. Documentation to follow.

**Comment by abitrolly** [comment]
An example would be nice.

**Comment by rvantonder** [comment]
Have a look at https://comby.dev/docs/configuration#toml-format. Going to close this issue since this will be the general file configuration format for now. Open any other suggestions/desires in a new issue based on this currently supported configuration format.
