### ISSUE TITLE
Simple OCaml example to run comby internal engine on a file

### ISSUE THREAD

**Issue by aryx** [comby-tools/comby#244]
I am thinking to integrate Comby inside semgrep (I think comby can benefit semgrep and semgrep benefit comby),
and I would like to integrate it by simply linking the Comby libraries in semgrep-core OCaml program.

I had a quick look at the .mli but could not find my way to call comby ...

Do you have a simple OCaml example of a program that just take 2 filenames, one containing a pattern
and one a target source file, and that would run the core matching engine of comby on this file.
Something like

```
let pattern = read_file "foo.pattern" in
let target = read_file "foo.c" in
let (matches_with_vars: Match.environment) = Comby.... ??? run_engine  pattern target in

**Comment by rvantonder** [comment]
Oh hai! 👋 

I think the interface you're looking for is `Matcher.all`, this takes the pattern (as string) and file contents (as string):

https://github.com/comby-tools/comby/blob/e6051e20f8f821f634b097f0252020bc044072e4/lib/matchers/types.ml#L124-L130

There is currently more than one engine for this interface, the one you want to use is

`Matchers.Alpha.<Language>.all ...`. E.g., with `utop-full`:

```ocaml
utop # #require "comby";;
utop # Matchers.Alpha.Generic.all;;
- : ?configuration:Matchers.Configuration.t ->
    ?nested:bool -> template:string -> source:string -> unit -> Match.t list
= <fun>
```


Here are the options for `<Language>`:

https://github.com/comby-tools/comby/blob/master/lib/matchers/types.ml#L136-L184. Use `select_with_extension` to get a matcher module for a particular language, e.g.,

```ocaml
let (module Rust_matcher : Matchers.Engine) = Matchers.Alpha.select_with_extension ".rs" in
Rust_matcher.all ...
```

(note the module syntax won't work in utop, but you get the idea). The string input should correspond to the extension output by `comby -list`, i.e., one of: `.rs`, `.c`, `.ml`, etc.

If you care only about match offsets and lengths, the above is enough. But if you need line/column conversion, then there's another function to run over matches to [hydrate line/column info in the result](https://sourcegraph.com/github.com/comby-tools/comby@master/-/blob/lib/match/match.mli#L71).

Note: the above won't apply anything in Comby's rule language to matches. That is currently a post processing step in [`timed_run` which is basically the toplevel function](https://github.com/comby-tools/comby/blob/master/lib/pipeline/pipeline.ml#L62). You can interface with this `timed_run` function too, the input parameters are similar, except that you would need to populate the `Specification.t` part, which is a bit more involved. 

Also comby is not packaged for opam yet 😞  Working on that this week in fact...

---

Would you like to just have a call/chat sometime? I'd be happy to.

**Comment by aryx** [comment]
Thanks a lot! An OPAM package would be awesome! I manage to compile comby from source but with all those pinned git dependencies, sometimes it broke.

Would love to chat. I'm working from Italy and I have some kids, so the best probably would be around my 5/6pm which should be your 9am in San Francisco (are you working from SF?)

**Comment by aryx** [comment]
I tried to write a simple test program using comby 1.3.0, but I get a linking error:
dune build
File "_none_", line 1:
Error: Required module `Camlzip__Zip' is unavailable
make: *** [Makefile:20: all] Error 1
Exited with status 2

I think it's because this Camlzip is not installed under .opam/.../lib/comby/

**Comment by aryx** [comment]
Just for reference @rvantonder here was the PR in semgrep trying to use comby: https://github.com/returntocorp/semgrep/pull/2844

**Comment by rvantonder** [comment]
> I think it's because this Camlzip is not installed under .opam/.../lib/comby/

Shoot! Will look into this soon.

**Comment by rvantonder** [comment]
https://github.com/comby-tools/comby/pull/263 should fix it, tested locally this time to make sure. Will upstream to opam soon.

**Comment by rvantonder** [comment]
`1.4.0` is mergd in opam and should be live soon. I had a look at the PR. This should give you a more complete idea of how to use things. Here I added a `metasyntax` definition that expects a `$` prefix for variables constrained to capitalized alphabetic characters. The `metasyntax` definition is passed to get a matcher, and currently needs to be passed to a separate `rewrite` call as well, if rewriting is needed (at some point I'll create a better interface so this isn't needed but that's how it is right now).

You can run this with `ocaml example.ml` since it uses the toplevel (or run inside `utop`).

```ocaml
#use "topfind";;
#thread;;
#require "comby";;

open Comby

let () =
  let open Matchers in
  let e = "go" in
  let metasyntax =
    Metasyntax.
      { syntax = [ Hole (Everything, Delimited (Some "$", None)) ]
      ; identifier = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      }
  in
  let (module M : Matcher.S) =
    match Alpha.select_with_extension ~metasyntax ("." ^ e) with
    | Some m -> m
    | None -> assert false
  in
  let source = "foo(bar, baz, qux)" in
  let match_template = "$A($B, $C)" in
  let rewrite_template = "$B($C)" in
  let matches = M.all ~template:match_template ~source () in
  (* print matches in JSON *)
  Format.printf "%a@." Match.pp_json_lines (None, matches);
  let replacement =
    match Rewrite.all ~metasyntax ~source ~rewrite_template matches with
    | Some r -> r
    | None -> assert false
  in
  (* print rewritten source *)
  Format.printf "%s@." replacement.rewritten_source
```

**Comment by rvantonder** [comment]
(There's more possibilities with the `metasyntax` definition I just gave a minimal example. See https://github.com/comby-tools/comby/blob/master/lib/comby.mli#L311-L319 and https://comby.dev/docs/syntax-reference to see what the supported semantic/matching behaviors are.

**Comment by aryx** [comment]
Ok this is great! It works now. I think you should put the example above somewhere in docs/ or demos/ or test/example.
I'll close the issue. Thanks a lot!

**Comment by aryx** [comment]
I have some bugs regarding line number and matching returned by the comby engine.
Here is my code:
https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/src/engine/Test_comby.ml

and on this js file:
```
function foo() {
    //ERROR:
    foo(1, 2)
    //unfortunately it does not match
    foo(1,2)

    //TODO should detect that:
    foo(1,
	2)

    //TODO that one too:
    foo (1, // comment
	 2)

    foo(2,1)
}
```
if I run 
```
/home/pad/yy/_build/default/src/cli/Main.exe -test_comby 'foo(1, 2)' tests/OTHER/rules/comby_basic.js
[0.128  Info       Main.Dune__exe__Main ] loaded log_config.json
[0.128  Info       Main.Dune__exe__Main ] Executed as: /home/pad/yy/_build/default/src/cli/Main.exe -test_comby foo(1, 2) tests/OTHER/rules/comby_basic.js
[0.128  Info       Main.Dune__exe__Main ] Version: semgrep-core version: v0.53.0-26-ga8b2db06-dirty, pfff: 0.42
{
  "uri": null,
  "matches": [
    {
      "range": {
        "start": {
          "offset": 34,
          "line": 1,
          "column": 35
        },
        "end": {
          "offset": 43,
          "line": 1,
          "column": 44
        }
      },
      "environment": [],
      "matched": "foo(1, 2)"
    },
    {
      "range": {
        "start": {
          "offset": 131,
          "line": 1,
          "column": 132
        },
        "end": {
          "offset": 141,
          "line": 2,
          "column": 4
        }
      },
      "environment": [],
      "matched": "foo(1,\\n\\t2)"
    }
  ]
}
```
you can see that the line number seems wrong and I also miss some matching.

I tried on the playground and I get different results.
Is it expected @rvantonder ?

**Comment by aryx** [comment]
Also I was surprised how comby is so space sensitive :(
bit.ly/3p8qz7g

**Comment by aryx** [comment]
ok, forget about my previous message, you mentioned it before:
> ...
> But if you need line/column conversion, then there's another function to run over matches to hydrate line/column info in the result.

**Comment by rvantonder** [comment]
> Comby is more space sensitive than I thought.

So there's actually an interesting design element here I think, which is that, indeed, the _concrete_ matching is more sensitive to whitespace because the assumptions about the significance of whitespace in the more coarse grammar are _less_ strict. To pose the converse: suppose that the intuitive matching worked in that example. If it did, it basically means that whitespace is treated _optionally_ around certain lexical constructs (in this case, comma `,`). But we can only treat whitespace optionally around those constructs if we know the underlying grammar allows it, otherwise, we cannot. For example, if we generalize this to a different syntax like `.`, perhaps a language allows dot access like `foo.bar.baz` or `foo.    bar     . baz` with spaces or newlines. If the presence of whitespace is significant here (it may or may not be), that might break the "intuitive" expectation of a user in the converse direction (why does `comby` match whitespace when I didn't tell it to?). 

So the short story is Comby doesn't attribute any different meaning to `,` versus `.` in a parse tree currently. Both of these are just lexical strings. Therefore, it doesn't make the assumption that whitespace may or may not be optional around these terms. Thinking about it more, it's probably a fairly safe assumption that separators _can_ contain optional whitespace _in general_ (so `,` and `;`, and maybe even `.`) but it is not an assumption `comby` has baked in now. It could be exposed as an option, and if it doesn't clash with intuitive expectation in most cases, can probably be a default.

All that said, it's actually also interesting because, I haven't had that many real use cases have issues with the current assumption.  Mostly because, I suspect, that because metavariables do consume whitespace and comments (or not), matching mostly aligns with intuitive expectation. I think there have been some uncommon cases where a logical `or` is needed, for example, to match expression in C with different styles around whitespace, like:

`if(cond)` and `if (cond)` could require two templates in comby (or, you can use optional regular expression syntax like `if:[~(\s+)?](cond)`). This is another example where, because `comby` uses a coarse grammar, it _won't_ make the assumption that `if(...)` and `if (...)` are equivalent (and it couldn't, it general), but for a language, like C, we have some intuition and perhaps in future it might be possible to communicate finer detail here to `comby` like 'hey, spaces are not significant between keywords `if` or between `(...)` or.... whatever the grammar allows'. For now, that's not possible. I think for the comma / comment case you gave it would be easy and mostly sensible to bake in at some point. Tradeoffs :-)
