### ISSUE TITLE
Not parsing correctly ruby block arguments.

### ISSUE THREAD

**Issue by diasbruno** [comby-tools/comby#298]
**Describe the bug**

Trying to match something like `:[[h]].each do |:[j]|` does not give any results.

I don't know if the pattern is incomplete or it's a problem interpreting `|args| `.

**Reproducing**

This matcher must produce a result `comby ":[[h]].each do |:[j]|" '' -matcher .rb`.

**Expected behavior**

Must produce a match.

**Comment by diasbruno** [comment]
I'd like to give it a try...can anyone give some pointers where I can start debugging this?

**Comment by rvantonder** [comment]
Hi there! I think you need your pattern to be:

`:[[h]].each do |:[j]| :[body] end` or, e.g., `:[[h]].each do |:[j]| ... end`

Without the `:[body] end`, comby has no way of really knowing you want to match an entire block. Because that original pattern starts with a `do`, but doesn't close it, `comby` won't find a match--to match blocks, the pattern must be complete with respect to the syntax that indicates a block (`do ... end`), and this is intended.

Alternatively you can search for `:[[h]].each do |:[j]|` textually by adding `-lang .txt`, if you only care about that string. But note that this may also match comments, strings, etc, it's basically grep.

**Comment by diasbruno** [comment]
Thanks. You are right. I thought I tried everything. [shell history](https://gist.github.com/diasbruno/a26a59acb843e7e1fd099f1cdbcb071d) 😆
