### ISSUE TITLE
Support for Julia?

### ISSUE THREAD

**Issue by pjgoodall** [comby-tools/comby#302]
I notice in your 2019 *Strange Loop* conference talk, Julia popped up in a list of languages that comby applied to. I have done quite a bit of searching to find out why Julia is not explicitly supported - no luck.

Can you give me an explanation please.

**Comment by rvantonder** [comment]
Hi 👋 What are the signs you're looking for to see whether Julia is supported or not? It does show up in the list of supported languages when you type `comby -list` or [overview in the docs](https://comby.dev/docs/overview). Do you get the impression it's not supported because it's not shown on [comby.live](https://comby.live/)? I can update that, just trying to clarify the source of confusion here.

**Comment by pjgoodall** [comment]
Yes, I was confused by it not being in the list on comby.live
Thanks…

**Comment by rvantonder** [comment]
Added it :-) https://comby.live
