### ISSUE TITLE
Whitespace argument matching

### ISSUE THREAD

**Issue by alexeygorskiy** [comby-tools/comby#324]
**Describe the bug**
Match templates are sensitive to whitespaces.

**Reproducing**
I am trying to match this: 
[bit.ly/3CR6CrE](https://comby.live/index.html#{%22source%22:%22smach.StateMachine.add('state_name',%20state_fn_call(),%20transitions={'done':'state_name'})\n%22,%22match%22:%22StateMachine.add(:[name],%20:[function_call],%20:[rest])%22,%22rule%22:%22where%20true%22,%22rewrite%22:%22STATE_NAME::[name]\nSTATE_FN_CALL::[function_call]\n:[rest]%22,%22language%22:%22.py%22,%22substitution_kind%22:%22in_place%22,%22id%22:0})

However, if I remove the whitespaces in the original code then it doesn't match anymore (removed whitespace in front of state_fn_call()): 
[bit.ly/3o03TWI](https://comby.live/index.html#{%22source%22:%22smach.StateMachine.add('state_name',state_fn_call(),%20transitions={'done':'state_name'})\n%22,%22match%22:%22StateMachine.add(:[name],%20:[function_call],%20:[rest])%22,%22rule%22:%22where%20true%22,%22rewrite%22:%22STATE_NAME::[name]\nSTATE_FN_CALL::[function_call]\n:[rest]%22,%22language%22:%22.py%22,%22substitution_kind%22:%22in_place%22,%22id%22:0})

To remedy that, I also need to remove the whitespace in the match template (removed whitespace in front of :[function_call]):
[bit.ly/3k9hlGM](https://comby.live/index.html#{%22source%22:%22smach.StateMachine.add('state_name',state_fn_call(),%20transitions={'done':'state_name'})\n%22,%22match%22:%22StateMachine.add(:[name],:[function_call],%20:[rest])%22,%22rule%22:%22where%20true%22,%22rewrite%22:%22STATE_NAME::[name]\nSTATE_FN_CALL::[function_call]\n:[rest]%22,%22language%22:%22.py%22,%22substitution_kind%22:%22in_place%22,%22id%22:0})

**Expected behavior**
I would expect Comby to identically match both cases with the same match template and not behave differently depending on whether there is a whitespace before the next argument in the code.

**Additional context**
I believe this to be a bug, but I am new to Comby so maybe this is intended behavior. If this is intended behavior, is there any away to make a generic matching template to match both cases with whitespaces and without whitespaces between the function arguments?

**Comment by rvantonder** [comment]
Hi 👋 

> I believe this to be a bug, but I am new to Comby so maybe this is intended behavior. 

This is not a bug, but indeed a limitation right now, as you point out. Comby is sensitive to the _presence_ of whitespace, but not the amount. There are only some contexts where "zero or more spaces" is desired, rather than "one or more spaces". Those contexts are typically cases like this, around separators `,` and, say, delimiters `(<optional space>...)`, but in other contexts, the presence of whitespace is significant. For example, `func foo` should not be treated as `funcfoo`. 

> I would expect Comby to identically match both cases with the same match template and not behave differently depending on whether there is a whitespace before the next argument in the code.

I have some work in progress, to make whitespace optional in certain contexts, like punctuation/separators/delimiters, but right now it's not possible.

My recommended fix is that you inline regular expressions that indeed tell comby that the whitespace is optional in these positions (i.e, before and after `,`). It doesn't look as pretty, but currently that's the only workaround, until I finish the work for making whitespace matching contextually parameterizable :-) Here is a single template, using inlined regex, that matches all those varieties: https://bit.ly/3kaMd9P

**Comment by alexeygorskiy** [comment]
Thank you for your help! That fixed my issue!

**Comment by sluukkonen** [comment]
I just tried using comby for the first time and noticed the same issue. If automatic support isn't in the near horizon, perhaps there could be some kind of shortcut for "zero or more whitespace" in the meanwhile? `:[~\s*]` is bit cumbersome to repeat multiple times in a template.

I have no opinions on the possible syntax though.

**Comment by acbits** [comment]
> I just tried using comby for the first time and noticed the same issue. If automatic support isn't in the near horizon, perhaps there could be some kind of shortcut for "zero or more whitespace" in the meanwhile? `:[~\s*]` is bit cumbersome to repeat multiple times in a template.
> 
> I have no opinions on the possible syntax though.

Just hit upon this issue after discovering comby. Is this issue fixed? 

zero or more whitespace should have been the default. Ideally, we should treat whitespace the same way the compiler of that specific language treats it.
