### ISSUE TITLE
Ability to drop/modify suffix?

### ISSUE THREAD

**Issue by jacobbednarz** [comby-tools/comby#378]
I've got a matcher that I'm using to rewrite parts of URLs to be consistent - [playground](https://comby.live/#%7B%22source%22%3A%22%20%20%2Faccounts%2F%7Bidentifier%7D%2Faccess%2Fapps%2F%7Bfoo%7D%3A%5Cn%20%20%20%20get%3A%5Cn%20%20%20%20%20%20tags%3A%5Cn%20%20%20%20%20%20-%20Accounts%5Cn%20%20%20%20%20%20summary%3A%20Account%20Details%5Cn%20%20%20%20%20%20description%3A%20Get%20information%20about%20a%20specific%20account%20that%20you%20are%20a%20member%5Cn%20%20%20%20%20%20%20%20of.%5Cn%20%20%20%20%20%20operationId%3A%20accounts-account-details%5Cn%20%20%20%20%20%20parameters%3A%5Cn%20%20%20%20%20%20-%20name%3A%20identifier%5Cn%20%20%20%20%20%20%20%20in%3A%20path%5Cn%20%20%20%20%20%20%20%20required%3A%20true%5Cn%20%20%20%20%20%20%20%20schema%3A%5Cn%20%20%20%20%20%20%20%20%20%20%24ref%3A%20'%23%2Fcomponents%2Fschemas%2FFCxrBfbu_schemas-identifier'%5Cn%20%20%20%20%20%20responses%3A%5Cn%20%20%20%20%20%20%20%204XX%3A%5Cn%20%20%20%20%20%20%20%20%20%20description%3A%20Account%20Details%20response%20failure%5Cn%20%20%20%20%20%20%20%20%20%20content%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20application%2Fjson%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20allOf%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%20%24ref%3A%20'%23%2Fcomponents%2Fschemas%2FFCxrBfbu_response_single'%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-%20%24ref%3A%20'%23%2Fcomponents%2Fschemas%2FFCxrBfbu_api-response-common-failure'%5Cn%20%20%20%20%20%20%20%20%5C%22200%5C%22%3A%5Cn%20%20%20%20%20%20%20%20%20%20description%3A%20Account%20Details%20response%5Cn%20%20%20%20%20%20%20%20%20%20content%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20application%2Fjson%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%24ref%3A%20'%23%2Fcomponents%2Fschemas%2FFCxrBfbu_response_single'%5Cn%20%20%20%20%20%20security%3A%5Cn%20%20%20%20%20%20-%20api_email%3A%20%5B%5D%5Cn%20%20%20%20%20%20%20%20api_key%3A%20%5B%5D%22%2C%22match%22%3A%22%2F%3A%5Btopic~%5C%5Cw%2B%5D%2F%7B%3A%5B_%5D%7D%22%2C%22rule%22%3A%22%22%2C%22rewrite%22%3A%22%2F%3A%5Btopic%5D%2F%7B%3A%5Btopic%5D_identifier%7D%22%2C%22language%22%3A%22.txt%22%2C%22substitution_kind%22%3A%22in_place%22%2C%22id%22%3A0%7D)

This is working 99% of the way there however, for `:[topic]` in the replacement, I'd like to drop the trailing "s" suffix if it exists.

Current: `/foos/{bar}/quaxs/{baz}` becomes `/foos/{foos_identifier}/quaxs/{quaxs_identifier}`
Desired: `/foos/{bar}/quaxs/{baz}` becomes `/foos/{foo_identifier}/quaxs/{quax_identifier}`

Are there any pointers or ideas on how I could achieve this within comby?

**Comment by rvantonder** [comment]
Hi @jacobbednarz! I would do it with a [rewrite rule](https://bit.ly/425htvt).

You can add this to the command line invocation with 

```
-rule 'where rewrite :[topic] { :[x]s -> :[x] }'
```

Basically, this rule fires and rewrites `topic` _if_ `:[x]s` matches and leaves it untouched otherwise.

Docs for this: https://comby.dev/docs/advanced-usage#rewrite-expressions

I thought about and tried regex with lookahead (comby supports perl regex in that syntax) and things like boundary assertions (but those don't seem to pan out and probably misleading / tricky behavior to reason about)

**Comment by jacobbednarz** [comment]
ah thank you! I didn't even click that a rule could be applicable here. appreciate it!

**Comment by jacobbednarz** [comment]
sorry for reusing this issue but i've got some behaviour here that i'm not sure about - https://bit.ly/3vGPy9f. 

my expectation is that `/zones/{foo}/rulesets/phases/{bar}/entrypoint/versions/{baz}` becomes `/zones/{zone_id}/rulesets/phases/{phase_id}/entrypoint/versions/{version_id}` however, for some reason, the "s" in the middle of these words is being targeted. am i holding this wrong? or is there a different syntax i should be using here instead?

**Comment by rvantonder** [comment]
hey @jacobbednarz, good question, it seems I simplified this in my head too early 😄 

I'll give a workaround before the longer explanation. It is a bit trickier to grok but I think it works in the general case:

https://bit.ly/47G5PbN

Basically, we make the `/` of the path part of the match, and then we can use that context to chop off an `s` before `/` (and not just _any_ `s`, which is what was happening before). Note the changes to the rule and the output pattern.

Strictly speaking you only need to match the trailing `/` so this also works:

https://bit.ly/48HAua6

Long explanation,

What was happening before is that, the way comby matches something like `:[x]s` is "match as much as possible until you see the thing after it (in this case `s`)". So when it matches against `phases`, it matches up to `pha`, sees an `s` after it, and stops. so we end up with two `:[x]s -> :[x]` happening twice for `phases` -> `[pha][e]`. But what we really want is only the last `s`. How do we know what is "last"? It turns out it's difficult to use regex or comby to say what is "last", and we don't have a "chop suffix" function or something like that yet. But based on your pattern, we know that a `/` means the s before it is "last", so we are using that fact to chop the suffix. Hope that helps

**Comment by jacobbednarz** [comment]
ah, that makes perfect sense! thanks again 🥇
