### ISSUE TITLE
Debugging rules that don't match as expected

### ISSUE THREAD

**Issue by mhlakhani** [comby-tools/comby#383]
Is there a good guide to debug *why* a rule isn't matching as expected? I'm running into a few types of issues and I can't seem to figure out how to file a good bug report yet. A few issues I have seen so far:

* I have a match that works in the playground, but when I run it against the same file locally it doesn't match
* I have a match that should match 3 instances but only matches 1

I would love to understand how to minify the bug report or debug this myself so I don't file a low quality bug report.

A concrete example I'm running into is bit.ly/41gNgLx -- it matches if I put `OtherRpc` in the rule, but if I rename it to `GetTestMessage` or `UpdateTestMessage` it doesn't match (or if I remove the rule). I don't see why, yet.

I also have a longer example where it **does** match `GetTestMessage` with the same rule/syntax but I haven't found a way to remove private info just yet.

**Comment by rvantonder** [comment]
The trouble in this case is to do with comments--the generic matcher doesn't recognize C-style comments, so their presence is messing up the matching.

[link](https://comby.live/#{%22source%22:%22service%20MyService%20{\n%20%20//%20Retrieves%20a%20message%20by%20it's%20ID.\n%20%20rpc%20GetTestMessageRpc(GetTestMessageRequest)%20returns%20(TestMessage)%20{\n%20%20};\n%20%20%20%20\n%20%20//%20Retrieves%20a%20message%20by%20it's%20ID.\n%20%20rpc%20OtherRpc(GetTestMessageRequest)%20returns%20(TestMessage)%20{\n%20%20};\n%20%20%20%20\n%20%20%20%20//%20Updates%20a%20message%20by%20it's%20ID.\n%20%20rpc%20UpdateTestMessage(GetTestMessageRequest)%20returns%20(TestMessage)%20{\n%20%20};\n}\n%22,%22match%22:%22rpc%20:[r](:[m])%20returns%20(:[rt])%20{:[body]}%22,%22rule%22:%22where%20:[r]%20==%20'GetTestMessageRpc'%22,%22rewrite%22:%22/*%20my%20new%20body%20*/%22,%22language%22:%22.c%22,%22substitution_kind%22:%22in_place%22,%22id%22:0})

I would use `-matcher .c` for proto files, since they adopt C-style comments (When I add `.proto` as a language in comby this will effectively be what happens)

There isn't really a way to debug why a rule doesn't match as expected, it's kind of like asking to debug parsing (difficulty level = hard to support a debugging experience for a user, you can instrument and compile from source but this is more likely to confuse than help unless you know how it all fits together). 

You might get some mileage by asking claude or chatgpt. 

that's really why the playground exists, for trial-by-error.

**Comment by mhlakhani** [comment]
Thanks! I can close this bug report out for now. Appreciate this!

(super minor nitpick -- your link correctly picked up the `.c` language, but the dropdown still showed `generic` -- would be nice if the dropdown prefilled from the UI)

**Comment by rvantonder** [comment]
thanks I realized that bug and actually pushed a fix before making this comment. If you hard-reload / refresh / incognito it should be working the way you describe

**Comment by mhlakhani** [comment]
can confirm it works - thanks!
