### ISSUE TITLE
Add or modify line-matcher to be zero-or-more instead of one-or-more followed by newline

### ISSUE THREAD

**Issue by virusdave** [comby-tools/comby#92]
I need to matching something top-level, but i need the context (right hand side) up to the next newline.  Sometimes this is empty.

Examples:
```
 val x = Some(42)
 val Some(x) = y
```
I need to be able to match something like `Some(:[param]):[rhs\n]`, because i need to examine the RHS in the where clause.

**Describe the solution you'd like**
Either modify https://github.com/comby-tools/comby/blob/master/lib/matchers/matcher.ml#L525 to be `many` instead of `many1`, or add a new hole syntax form (perhaps `:[id?\n]` to make it zero-or-more instead of one-or-more.

**Comment by rvantonder** [comment]
The change to make `:[hole\n]` match the empty string before a newline makes sense. Done in #93. Note that currently, `:[hole\n]` captures the newline as well. So testing `where :[hole] { | "\n" -> true }` satisfies the empty string case. I think there's a case to be made for stripping the matched newline from anything matched by `:[hole\n]` (instead of capturing the newline), but that differs more from the current behavior, and needs additional changes.

Aside: in general, I'm cautious about introducing new syntax, and especially optional syntax. I'll write out some guidelines around this thinking in the next day or two. Down the line, there may be a case for an escape hatch in the syntax that supports arbitrary regex, but I think discussions around those things would be helpful and in favoring of erring on the side of caution :)

**Comment by rvantonder** [comment]
Closing for now--feel free to comment or reopen if there are lingering thoughts. I'll cut a release at the end of the week, probably.
